const Equality=[
    {
        "scheme_name": "Aditya Birla SL Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "1000",
        "expense_ratio": "0.36",
        "fund_size_cr": "4288",
        "fund_age_yr": "10",
        "fund_manager": "Lovelish Solanki",
        "sortino": "1.33",
        "alpha": "1.53",
        "sd": "0.72",
        "beta": "0.56",
        "sharpe": "1.1",
        "risk_level": "1",
        "amc_name": "Aditya Birla Sun Life Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.6",
        "returns_3yr": "4.8",
        "returns_5yr": "5.5"
    },
    {
        "scheme_name": "Aditya Birla SL Balanced Advantage Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "0.61",
        "fund_size_cr": "6386",
        "fund_age_yr": "10",
        "fund_manager": "Mohit Sharma",
        "sortino": "3.69",
        "alpha": "1.99",
        "sd": "10.38",
        "beta": "0.68",
        "sharpe": "1.39",
        "risk_level": "6",
        "amc_name": "Aditya Birla Sun Life Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "4.5",
        "returns_3yr": "18.6",
        "returns_5yr": "9.7"
    },
    {
        "scheme_name": "Aditya Birla SL Equity Hybrid â€™95 Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "1.01",
        "fund_size_cr": "7046",
        "fund_age_yr": "10",
        "fund_manager": "Mahesh Patil",
        "sortino": "2.54",
        "alpha": "1.43",
        "sd": "12.84",
        "beta": "0.85",
        "sharpe": "1.33",
        "risk_level": "6",
        "amc_name": "Aditya Birla Sun Life Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "-5.7",
        "returns_3yr": "20.4",
        "returns_5yr": "7.7"
    },
    {
        "scheme_name": "Aditya Birla SL Equity Savings Fund",
        "min_sip": "1000",
        "min_lumpsum": "1000",
        "expense_ratio": "1.21",
        "fund_size_cr": "451",
        "fund_age_yr": "8",
        "fund_manager": "Dhaval Shah",
        "sortino": "2.55",
        "alpha": "1.11",
        "sd": "6.83",
        "beta": "0.99",
        "sharpe": "1.2",
        "risk_level": "4",
        "amc_name": "Aditya Birla Sun Life Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "0.8",
        "returns_3yr": "11.7",
        "returns_5yr": "6.9"
    },
    {
        "scheme_name": "Aditya Birla SL Regular Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "0.92",
        "fund_size_cr": "1585",
        "fund_age_yr": "10",
        "fund_manager": "Dhaval Shah",
        "sortino": "3.88",
        "alpha": "5.71",
        "sd": "4.8",
        "beta": "0.6",
        "sharpe": "2.08",
        "risk_level": "4",
        "amc_name": "Aditya Birla Sun Life Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "3.6",
        "returns_3yr": "13.9",
        "returns_5yr": "7.6"
    },
    {
        "scheme_name": "AXIS Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.31",
        "fund_size_cr": "3085",
        "fund_age_yr": "9",
        "fund_manager": "Ashish Naik",
        "sortino": "1.47",
        "alpha": "1.41",
        "sd": "0.68",
        "beta": "0.44",
        "sharpe": "1.21",
        "risk_level": "1",
        "amc_name": "Axis Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.6",
        "returns_3yr": "4.9",
        "returns_5yr": "5.6"
    },
    {
        "scheme_name": "AXIS Balanced Advantage Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.7",
        "fund_size_cr": "2077",
        "fund_age_yr": "6",
        "fund_manager": "Anupam Tiwari",
        "sortino": "2.26",
        "alpha": "-1.23",
        "sd": "8.09",
        "beta": "0.53",
        "sharpe": "1.05",
        "risk_level": "6",
        "amc_name": "Axis Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "1.2",
        "returns_3yr": "12.4",
        "returns_5yr": "8"
    },
    {
        "scheme_name": "AXIS Equity Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.89",
        "fund_size_cr": "1699",
        "fund_age_yr": "5",
        "fund_manager": "Ashish Naik",
        "sortino": "2.37",
        "alpha": "-1.88",
        "sd": "13",
        "beta": "0.87",
        "sharpe": "1.09",
        "risk_level": "6",
        "amc_name": "Axis Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "-4.9",
        "returns_3yr": "17.4",
        "returns_5yr": ""
    },
    {
        "scheme_name": "AXIS Equity Saver Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.88",
        "fund_size_cr": "978",
        "fund_age_yr": "8",
        "fund_manager": "R Sivakumar",
        "sortino": "2.39",
        "alpha": "0.66",
        "sd": "7.52",
        "beta": "1.16",
        "sharpe": "1.19",
        "risk_level": "4",
        "amc_name": "Axis Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "1.4",
        "returns_3yr": "12.7",
        "returns_5yr": "8.8"
    },
    {
        "scheme_name": "AXIS Regular Saver Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.86",
        "fund_size_cr": "407",
        "fund_age_yr": "10",
        "fund_manager": "Devang Shah",
        "sortino": "2.42",
        "alpha": "1.34",
        "sd": "4.69",
        "beta": "0.71",
        "sharpe": "1.37",
        "risk_level": "4",
        "amc_name": "Axis Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "1.8",
        "returns_3yr": "10.9",
        "returns_5yr": "7"
    },
    {
        "scheme_name": "AXIS Triple Advantage Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.72",
        "fund_size_cr": "1478",
        "fund_age_yr": "10",
        "fund_manager": "R Sivakumar",
        "sortino": "2.35",
        "alpha": "-2.21",
        "sd": "13.44",
        "beta": "0.91",
        "sharpe": "1.08",
        "risk_level": "6",
        "amc_name": "Axis Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Multi Asset Allocation Mutual Funds",
        "returns_1yr": "-5.1",
        "returns_3yr": "18.1",
        "returns_5yr": "10.4"
    },
    {
        "scheme_name": "Bank of India Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.98",
        "fund_size_cr": "12",
        "fund_age_yr": "5",
        "fund_manager": "Alok Singh",
        "sortino": "-1.14",
        "alpha": "0.24",
        "sd": "0.6",
        "beta": "0.52",
        "sharpe": "-0.78",
        "risk_level": "1",
        "amc_name": "Bank of India Mutual Fund",
        "rating": "1",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "4.2",
        "returns_3yr": "3.4",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Bank of India Balanced Advantage Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "2.07",
        "fund_size_cr": "90",
        "fund_age_yr": "9",
        "fund_manager": "Alok Singh",
        "sortino": "1.81",
        "alpha": "-1.05",
        "sd": "11.04",
        "beta": "0.54",
        "sharpe": "0.81",
        "risk_level": "6",
        "amc_name": "Bank of India Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "13.6",
        "returns_3yr": "12.1",
        "returns_5yr": "5.1"
    },
    {
        "scheme_name": "Bank of India Conservative Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "10000",
        "expense_ratio": "2.2",
        "fund_size_cr": "63",
        "fund_age_yr": "10",
        "fund_manager": "Alok Singh",
        "sortino": "4.71",
        "alpha": "6.44",
        "sd": "11.85",
        "beta": "0.64",
        "sharpe": "0.93",
        "risk_level": "3",
        "amc_name": "Bank of India Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "22.3",
        "returns_3yr": "15.5",
        "returns_5yr": "6.4"
    },
    {
        "scheme_name": "Bank of India Mid & Small Cap Equity & Debt Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "1.92",
        "fund_size_cr": "380",
        "fund_age_yr": "7",
        "fund_manager": "Alok Singh",
        "sortino": "2.56",
        "alpha": "10.87",
        "sd": "15.51",
        "beta": "0.75",
        "sharpe": "1.59",
        "risk_level": "6",
        "amc_name": "Bank of India Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "-0.3",
        "returns_3yr": "29.3",
        "returns_5yr": "10.4"
    },
    {
        "scheme_name": "Baroda BNP Paribas Aggressive Hybrid Fund",
        "min_sip": "300",
        "min_lumpsum": "5000",
        "expense_ratio": "0.61",
        "fund_size_cr": "772",
        "fund_age_yr": "6",
        "fund_manager": "Jitendra Sriram",
        "sortino": "2.79",
        "alpha": "1.88",
        "sd": "11.77",
        "beta": "0.79",
        "sharpe": "1.39",
        "risk_level": "6",
        "amc_name": "Baroda BNP Paribas Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "3.5",
        "returns_3yr": "20.6",
        "returns_5yr": "13.3"
    },
    {
        "scheme_name": "Baroda BNP Paribas Arbitrage Fund",
        "min_sip": "300",
        "min_lumpsum": "5000",
        "expense_ratio": "0.49",
        "fund_size_cr": "354",
        "fund_age_yr": "6",
        "fund_manager": "Neeraj Saxena",
        "sortino": "0.99",
        "alpha": "1.39",
        "sd": "0.71",
        "beta": "0.59",
        "sharpe": "0.85",
        "risk_level": "1",
        "amc_name": "Baroda BNP Paribas Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.2",
        "returns_3yr": "4.6",
        "returns_5yr": "5.6"
    },
    {
        "scheme_name": "Baroda BNP Paribas Balanced Advantage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.64",
        "fund_size_cr": "3123",
        "fund_age_yr": "4",
        "fund_manager": "Sanjay Chawla",
        "sortino": "3.41",
        "alpha": "2.61",
        "sd": "10.57",
        "beta": "0.7",
        "sharpe": "1.46",
        "risk_level": "6",
        "amc_name": "Baroda BNP Paribas Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "3.7",
        "returns_3yr": "19.8",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Baroda BNP Paribas Conservative Hybrid Fund",
        "min_sip": "300",
        "min_lumpsum": "1000",
        "expense_ratio": "0.78",
        "fund_size_cr": "501",
        "fund_age_yr": "10",
        "fund_manager": "Pratish Krishnan",
        "sortino": "2.74",
        "alpha": "0.64",
        "sd": "3.7",
        "beta": "0.58",
        "sharpe": "1.29",
        "risk_level": "4",
        "amc_name": "Baroda BNP Paribas Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "3.7",
        "returns_3yr": "9.2",
        "returns_5yr": "7.7"
    },
    {
        "scheme_name": "Baroda BNP Paribas Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1.45",
        "fund_size_cr": "250",
        "fund_age_yr": "4",
        "fund_manager": "Pratish Krishnan",
        "sortino": "2.42",
        "alpha": "0.25",
        "sd": "4.91",
        "beta": "0.73",
        "sharpe": "1.12",
        "risk_level": "4",
        "amc_name": "Baroda BNP Paribas Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "3.7",
        "returns_3yr": "9.8",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Canara Robeco Conservative Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.57",
        "fund_size_cr": "1069",
        "fund_age_yr": "10",
        "fund_manager": "Avnish Jain",
        "sortino": "3.41",
        "alpha": "2.59",
        "sd": "3.98",
        "beta": "0.6",
        "sharpe": "1.74",
        "risk_level": "4",
        "amc_name": "Canara Robeco Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "3.8",
        "returns_3yr": "11.4",
        "returns_5yr": "9.4"
    },
    {
        "scheme_name": "Canara Robeco Equity Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.63",
        "fund_size_cr": "8235",
        "fund_age_yr": "10",
        "fund_manager": "Shridatta Bhandwaldar",
        "sortino": "3.25",
        "alpha": "1.49",
        "sd": "11.27",
        "beta": "0.78",
        "sharpe": "1.4",
        "risk_level": "6",
        "amc_name": "Canara Robeco Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "1.8",
        "returns_3yr": "20.1",
        "returns_5yr": "12.2"
    },
    {
        "scheme_name": "DSP Arbitrage Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "0.35",
        "fund_size_cr": "1238",
        "fund_age_yr": "5",
        "fund_manager": "Kedar Karnik",
        "sortino": "1.08",
        "alpha": "1.45",
        "sd": "0.72",
        "beta": "0.64",
        "sharpe": "0.82",
        "risk_level": "1",
        "amc_name": "DSP Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.6",
        "returns_3yr": "4.6",
        "returns_5yr": "5.4"
    },
    {
        "scheme_name": "DSP Dynamic Asset Allocation Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "0.71",
        "fund_size_cr": "3770",
        "fund_age_yr": "9",
        "fund_manager": "Atul Bhole",
        "sortino": "2.7",
        "alpha": "-0.92",
        "sd": "8.62",
        "beta": "0.53",
        "sharpe": "1.03",
        "risk_level": "5",
        "amc_name": "DSP Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "1.7",
        "returns_3yr": "12.2",
        "returns_5yr": "8.3"
    },
    {
        "scheme_name": "DSP Equity & Bond Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "0.78",
        "fund_size_cr": "7358",
        "fund_age_yr": "10",
        "fund_manager": "Atul Bhole",
        "sortino": "2.7",
        "alpha": "0.51",
        "sd": "12.7",
        "beta": "0.83",
        "sharpe": "1.25",
        "risk_level": "6",
        "amc_name": "DSP Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "0.6",
        "returns_3yr": "18.7",
        "returns_5yr": "10.7"
    },
    {
        "scheme_name": "DSP Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "0.4",
        "fund_size_cr": "535",
        "fund_age_yr": "7",
        "fund_manager": "Kedar Karnik",
        "sortino": "3.55",
        "alpha": "4.83",
        "sd": "6.37",
        "beta": "0.88",
        "sharpe": "1.75",
        "risk_level": "4",
        "amc_name": "DSP Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "4",
        "returns_3yr": "14.6",
        "returns_5yr": "7.8"
    },
    {
        "scheme_name": "DSP Regular Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "0.51",
        "fund_size_cr": "199",
        "fund_age_yr": "10",
        "fund_manager": "Vikram Chopra",
        "sortino": "2.68",
        "alpha": "2.26",
        "sd": "4.28",
        "beta": "0.61",
        "sharpe": "1.55",
        "risk_level": "3",
        "amc_name": "DSP Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "3",
        "returns_3yr": "10.8",
        "returns_5yr": "6"
    },
    {
        "scheme_name": "Edelweiss Aggressive Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.36",
        "fund_size_cr": "469",
        "fund_age_yr": "10",
        "fund_manager": "Bharat Lahoti",
        "sortino": "3.83",
        "alpha": "5.57",
        "sd": "11.66",
        "beta": "0.79",
        "sharpe": "1.72",
        "risk_level": "6",
        "amc_name": "Edelweiss Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "6.5",
        "returns_3yr": "24.6",
        "returns_5yr": "13"
    },
    {
        "scheme_name": "Edelweiss Arbitrage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.37",
        "fund_size_cr": "5393",
        "fund_age_yr": "9",
        "fund_manager": "Bhavesh Jain",
        "sortino": "1.61",
        "alpha": "1.78",
        "sd": "0.72",
        "beta": "0.63",
        "sharpe": "1.31",
        "risk_level": "1",
        "amc_name": "Edelweiss Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.8",
        "returns_3yr": "5",
        "returns_5yr": "5.7"
    },
    {
        "scheme_name": "Edelweiss Balanced Advantage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.51",
        "fund_size_cr": "8780",
        "fund_age_yr": "10",
        "fund_manager": "Bhavesh Jain",
        "sortino": "3.31",
        "alpha": "2.1",
        "sd": "9.71",
        "beta": "0.67",
        "sharpe": "1.48",
        "risk_level": "6",
        "amc_name": "Edelweiss Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "2.9",
        "returns_3yr": "18.5",
        "returns_5yr": "12"
    },
    {
        "scheme_name": "Edelweiss Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.7",
        "fund_size_cr": "258",
        "fund_age_yr": "8",
        "fund_manager": "Bharat Lahoti",
        "sortino": "3.22",
        "alpha": "2.41",
        "sd": "5.29",
        "beta": "0.79",
        "sharpe": "1.53",
        "risk_level": "4",
        "amc_name": "Edelweiss Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "4.4",
        "returns_3yr": "12.1",
        "returns_5yr": "9"
    },
    {
        "scheme_name": "Franklin India Debt Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "10000",
        "expense_ratio": "0.57",
        "fund_size_cr": "246",
        "fund_age_yr": "10",
        "fund_manager": "Rajasa Kakulavarapu",
        "sortino": "2.98",
        "alpha": "1.26",
        "sd": "3.89",
        "beta": "0.59",
        "sharpe": "1.42",
        "risk_level": "4",
        "amc_name": "Franklin Templeton Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "5.1",
        "returns_3yr": "9.8",
        "returns_5yr": "7"
    },
    {
        "scheme_name": "Franklin India Equity Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1.2",
        "fund_size_cr": "1347",
        "fund_age_yr": "10",
        "fund_manager": "Rajasa Kakulavarapu",
        "sortino": "3.24",
        "alpha": "3.49",
        "sd": "12.1",
        "beta": "0.8",
        "sharpe": "1.51",
        "risk_level": "6",
        "amc_name": "Franklin Templeton Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "5.3",
        "returns_3yr": "22.5",
        "returns_5yr": "11"
    },
    {
        "scheme_name": "Franklin India Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.71",
        "fund_size_cr": "153",
        "fund_age_yr": "5",
        "fund_manager": "Rajasa Kakulavarapu",
        "sortino": "3.01",
        "alpha": "3.39",
        "sd": "6.61",
        "beta": "0.94",
        "sharpe": "1.53",
        "risk_level": "3",
        "amc_name": "Franklin Templeton Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "4.8",
        "returns_3yr": "14",
        "returns_5yr": ""
    },
    {
        "scheme_name": "HDFC Arbitrage Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "0.43",
        "fund_size_cr": "5886",
        "fund_age_yr": "9",
        "fund_manager": "Arun Agarwal",
        "sortino": "0.99",
        "alpha": "1.24",
        "sd": "0.7",
        "beta": "0.5",
        "sharpe": "0.82",
        "risk_level": "1",
        "amc_name": "HDFC Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.6",
        "returns_3yr": "4.5",
        "returns_5yr": "5.2"
    },
    {
        "scheme_name": "HDFC Balanced Advantage Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "0.88",
        "fund_size_cr": "51042",
        "fund_age_yr": "10",
        "fund_manager": "Gopal Agrawal",
        "sortino": "3.38",
        "alpha": "7.38",
        "sd": "14.82",
        "beta": "0.88",
        "sharpe": "1.6",
        "risk_level": "6",
        "amc_name": "HDFC Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "14.4",
        "returns_3yr": "29.3",
        "returns_5yr": "12.9"
    },
    {
        "scheme_name": "HDFC Equity Savings Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "1.1",
        "fund_size_cr": "2524",
        "fund_age_yr": "10",
        "fund_manager": "Anil Bamboli",
        "sortino": "3.67",
        "alpha": "4.42",
        "sd": "7.09",
        "beta": "0.98",
        "sharpe": "1.61",
        "risk_level": "4",
        "amc_name": "HDFC Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "5.1",
        "returns_3yr": "16",
        "returns_5yr": "8.8"
    },
    {
        "scheme_name": "HDFC Hybrid Debt Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "1.33",
        "fund_size_cr": "2695",
        "fund_age_yr": "10",
        "fund_manager": "Shobhit Mehrotra",
        "sortino": "3.46",
        "alpha": "3.73",
        "sd": "4.97",
        "beta": "0.69",
        "sharpe": "1.74",
        "risk_level": "4",
        "amc_name": "HDFC Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "6",
        "returns_3yr": "13.3",
        "returns_5yr": "8.4"
    },
    {
        "scheme_name": "HDFC Hybrid Equity Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "1.09",
        "fund_size_cr": "18729",
        "fund_age_yr": "10",
        "fund_manager": "Chirag Setalvad",
        "sortino": "3.42",
        "alpha": "4.86",
        "sd": "13.03",
        "beta": "0.87",
        "sharpe": "1.6",
        "risk_level": "6",
        "amc_name": "HDFC Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "7.7",
        "returns_3yr": "25.6",
        "returns_5yr": "11.3"
    },
    {
        "scheme_name": "HDFC Multi-Asset Fund",
        "min_sip": "100",
        "min_lumpsum": "100",
        "expense_ratio": "0.88",
        "fund_size_cr": "1643",
        "fund_age_yr": "10",
        "fund_manager": "Srinivasan Ramamurthy",
        "sortino": "4.21",
        "alpha": "5.06",
        "sd": "11.41",
        "beta": "0.72",
        "sharpe": "1.6",
        "risk_level": "6",
        "amc_name": "HDFC Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Multi Asset Allocation Mutual Funds",
        "returns_1yr": "6.9",
        "returns_3yr": "23",
        "returns_5yr": "10.9"
    },
    {
        "scheme_name": "HSBC Aggressive Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.87",
        "fund_size_cr": "4636",
        "fund_age_yr": "10",
        "fund_manager": "Shriram Ramanathan",
        "sortino": "2.41",
        "alpha": "0.57",
        "sd": "12.27",
        "beta": "0.81",
        "sharpe": "1.26",
        "risk_level": "6",
        "amc_name": "HSBC Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "-1.2",
        "returns_3yr": "19.5",
        "returns_5yr": "8.1"
    },
    {
        "scheme_name": "HSBC Arbitrage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.29",
        "fund_size_cr": "2344",
        "fund_age_yr": "9",
        "fund_manager": "Ritesh Jain",
        "sortino": "1.54",
        "alpha": "1.63",
        "sd": "0.7",
        "beta": "0.63",
        "sharpe": "1.12",
        "risk_level": "1",
        "amc_name": "HSBC Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.4",
        "returns_3yr": "4.7",
        "returns_5yr": "5.5"
    },
    {
        "scheme_name": "HSBC Balanced Advantage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.78",
        "fund_size_cr": "1511",
        "fund_age_yr": "10",
        "fund_manager": "Ritesh Jain",
        "sortino": "2.95",
        "alpha": "0.89",
        "sd": "7.21",
        "beta": "0.45",
        "sharpe": "1.27",
        "risk_level": "4",
        "amc_name": "HSBC Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "3.5",
        "returns_3yr": "13.4",
        "returns_5yr": "8"
    },
    {
        "scheme_name": "HSBC Conservative Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1.34",
        "fund_size_cr": "122",
        "fund_age_yr": "10",
        "fund_manager": "Ritesh Jain",
        "sortino": "2.3",
        "alpha": "0.76",
        "sd": "4.75",
        "beta": "0.74",
        "sharpe": "1.28",
        "risk_level": "4",
        "amc_name": "HSBC Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "2.3",
        "returns_3yr": "10.3",
        "returns_5yr": "7.5"
    },
    {
        "scheme_name": "HSBC Equity Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1",
        "fund_size_cr": "474",
        "fund_age_yr": "4",
        "fund_manager": "Neelotpal Sahai",
        "sortino": "2.41",
        "alpha": "0.57",
        "sd": "12.27",
        "beta": "0.81",
        "sharpe": "1.26",
        "risk_level": "6",
        "amc_name": "HSBC Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "1.7",
        "returns_3yr": "32.4",
        "returns_5yr": "13.3"
    },
    {
        "scheme_name": "HSBC Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.62",
        "fund_size_cr": "150",
        "fund_age_yr": "10",
        "fund_manager": "Ritesh Jain",
        "sortino": "4.47",
        "alpha": "5.57",
        "sd": "6.24",
        "beta": "0.85",
        "sharpe": "1.86",
        "risk_level": "3",
        "amc_name": "HSBC Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "2.9",
        "returns_3yr": "15.5",
        "returns_5yr": "7.5"
    },
    {
        "scheme_name": "ICICI Pru Balanced Advantage Fund",
        "min_sip": "100",
        "min_lumpsum": "500",
        "expense_ratio": "0.91",
        "fund_size_cr": "44515",
        "fund_age_yr": "10",
        "fund_manager": "Sankaran Naren",
        "sortino": "5.59",
        "alpha": "5.34",
        "sd": "8.33",
        "beta": "0.54",
        "sharpe": "1.84",
        "risk_level": "5",
        "amc_name": "ICICI Prudential Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "6.7",
        "returns_3yr": "19.7",
        "returns_5yr": "10.4"
    },
    {
        "scheme_name": "ICICI Pru Equity & Debt Fund",
        "min_sip": "100",
        "min_lumpsum": "5000",
        "expense_ratio": "1.2",
        "fund_size_cr": "21232",
        "fund_age_yr": "10",
        "fund_manager": "Sankaran Naren",
        "sortino": "4.15",
        "alpha": "9.56",
        "sd": "14.26",
        "beta": "0.84",
        "sharpe": "1.75",
        "risk_level": "6",
        "amc_name": "ICICI Prudential Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "6.8",
        "returns_3yr": "30.6",
        "returns_5yr": "14.3"
    },
    {
        "scheme_name": "ICICI Pru Equity â€“ Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.39",
        "fund_size_cr": "11272",
        "fund_age_yr": "10",
        "fund_manager": "Kayzad Eghlim",
        "sortino": "1.27",
        "alpha": "1.59",
        "sd": "0.75",
        "beta": "0.63",
        "sharpe": "0.99",
        "risk_level": "1",
        "amc_name": "ICICI Prudential Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.6",
        "returns_3yr": "4.8",
        "returns_5yr": "5.5"
    },
    {
        "scheme_name": "ICICI Pru Equity Savings Fund",
        "min_sip": "100",
        "min_lumpsum": "5000",
        "expense_ratio": "0.54",
        "fund_size_cr": "4936",
        "fund_age_yr": "8",
        "fund_manager": "Kayzad Eghlim",
        "sortino": "5.26",
        "alpha": "4.82",
        "sd": "4.82",
        "beta": "0.57",
        "sharpe": "1.84",
        "risk_level": "2",
        "amc_name": "ICICI Prudential Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "6.2",
        "returns_3yr": "12.7",
        "returns_5yr": "7.9"
    },
    {
        "scheme_name": "ICICI Pru Multi-Asset Fund",
        "min_sip": "100",
        "min_lumpsum": "5000",
        "expense_ratio": "1.15",
        "fund_size_cr": "16449",
        "fund_age_yr": "10",
        "fund_manager": "Sankaran Naren",
        "sortino": "3.99",
        "alpha": "10.44",
        "sd": "13.67",
        "beta": "0.81",
        "sharpe": "1.85",
        "risk_level": "6",
        "amc_name": "ICICI Prudential Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Multi Asset Allocation Mutual Funds",
        "returns_1yr": "11.3",
        "returns_3yr": "31.3",
        "returns_5yr": "14.2"
    },
    {
        "scheme_name": "ICICI Pru Regular Savings Fund",
        "min_sip": "100",
        "min_lumpsum": "5000",
        "expense_ratio": "0.99",
        "fund_size_cr": "3212",
        "fund_age_yr": "10",
        "fund_manager": "Manish Banthia",
        "sortino": "3.57",
        "alpha": "3.21",
        "sd": "3.41",
        "beta": "0.5",
        "sharpe": "2",
        "risk_level": "4",
        "amc_name": "ICICI Prudential Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "5.5",
        "returns_3yr": "11.3",
        "returns_5yr": "9"
    },
    {
        "scheme_name": "IDBI Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1.15",
        "fund_size_cr": "9.77",
        "fund_age_yr": "10",
        "fund_manager": "Alok Ranjan",
        "sortino": "2.48",
        "alpha": "0.39",
        "sd": "7.12",
        "beta": "1.05",
        "sharpe": "1.11",
        "risk_level": "4",
        "amc_name": "IDBI Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "2.5",
        "returns_3yr": "11.8",
        "returns_5yr": "7.2"
    },
    {
        "scheme_name": "IDBI Hybrid Equity Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1.67",
        "fund_size_cr": "171",
        "fund_age_yr": "6",
        "fund_manager": "Alok Ranjan",
        "sortino": "2.66",
        "alpha": "-0.86",
        "sd": "11.4",
        "beta": "0.78",
        "sharpe": "1.18",
        "risk_level": "6",
        "amc_name": "IDBI Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "-1.8",
        "returns_3yr": "17.5",
        "returns_5yr": "7"
    },
    {
        "scheme_name": "Indiabulls Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "500",
        "expense_ratio": "0.58",
        "fund_size_cr": "14",
        "fund_age_yr": "8",
        "fund_manager": "Sumit Bhatnagar",
        "sortino": "-1.04",
        "alpha": "0.18",
        "sd": "0.67",
        "beta": "0.54",
        "sharpe": "-0.82",
        "risk_level": "1",
        "amc_name": "Indiabulls Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "4.3",
        "returns_3yr": "3.3",
        "returns_5yr": "4.5"
    },
    {
        "scheme_name": "Indiabulls Equity Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "500",
        "expense_ratio": "1.55",
        "fund_size_cr": "32",
        "fund_age_yr": "4",
        "fund_manager": "Sumit Bhatnagar",
        "sortino": "2.77",
        "alpha": "0.47",
        "sd": "12.71",
        "beta": "0.87",
        "sharpe": "1.29",
        "risk_level": "5",
        "amc_name": "Indiabulls Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "3.2",
        "returns_3yr": "20.5",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Invesco India Arbitrage Fund",
        "min_sip": "500",
        "min_lumpsum": "1000",
        "expense_ratio": "0.38",
        "fund_size_cr": "3184",
        "fund_age_yr": "10",
        "fund_manager": "Deepak Gupta",
        "sortino": "2.16",
        "alpha": "1.77",
        "sd": "0.71",
        "beta": "0.53",
        "sharpe": "1.5",
        "risk_level": "1",
        "amc_name": "Invesco Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "6.4",
        "returns_3yr": "5",
        "returns_5yr": "5.6"
    },
    {
        "scheme_name": "Invesco India Dynamic Equity Fund",
        "min_sip": "500",
        "min_lumpsum": "1000",
        "expense_ratio": "0.95",
        "fund_size_cr": "612",
        "fund_age_yr": "10",
        "fund_manager": "Amit Ganatra",
        "sortino": "2.84",
        "alpha": "0.76",
        "sd": "9.2",
        "beta": "0.59",
        "sharpe": "1.27",
        "risk_level": "6",
        "amc_name": "Invesco Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "3.9",
        "returns_3yr": "15.4",
        "returns_5yr": "7.4"
    },
    {
        "scheme_name": "Invesco India Equity & Bond Fund",
        "min_sip": "500",
        "min_lumpsum": "1000",
        "expense_ratio": "0.76",
        "fund_size_cr": "378",
        "fund_age_yr": "5",
        "fund_manager": "Dhimant Kothari",
        "sortino": "2.71",
        "alpha": "1.1",
        "sd": "10.94",
        "beta": "0.71",
        "sharpe": "1.29",
        "risk_level": "6",
        "amc_name": "Invesco Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "1.5",
        "returns_3yr": "17.4",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Invesco India Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "1000",
        "expense_ratio": "0.73",
        "fund_size_cr": "132",
        "fund_age_yr": "4",
        "fund_manager": "Dhimant Kothari",
        "sortino": "1.9",
        "alpha": "0.17",
        "sd": "5.58",
        "beta": "0.82",
        "sharpe": "1.08",
        "risk_level": "4",
        "amc_name": "Invesco Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "1.2",
        "returns_3yr": "9.6",
        "returns_5yr": ""
    },
    {
        "scheme_name": "ITI Arbitrage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.22",
        "fund_size_cr": "7.04",
        "fund_age_yr": "4",
        "fund_manager": "Vikrant Mehta",
        "sortino": "-1.02",
        "alpha": "-0.04",
        "sd": "0.65",
        "beta": "0.31",
        "sharpe": "-0.71",
        "risk_level": "1",
        "amc_name": "ITI Mutual Fund",
        "rating": "1",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "3.9",
        "returns_3yr": "3.3",
        "returns_5yr": ""
    },
    {
        "scheme_name": "ITI Balanced Advantage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.35",
        "fund_size_cr": "452",
        "fund_age_yr": "3",
        "fund_manager": "Dhimant Shah",
        "sortino": "2.56",
        "alpha": "-0.95",
        "sd": "11.13",
        "beta": "0.59",
        "sharpe": "0.88",
        "risk_level": "6",
        "amc_name": "ITI Mutual Fund",
        "rating": "1",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "-0.2",
        "returns_3yr": "12.3",
        "returns_5yr": ""
    },
    {
        "scheme_name": "JM Arbitrage Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "0.36",
        "fund_size_cr": "60",
        "fund_age_yr": "10",
        "fund_manager": "Asit Bhandarkar",
        "sortino": "-0.31",
        "alpha": "0.56",
        "sd": "0.72",
        "beta": "0.55",
        "sharpe": "-0.23",
        "risk_level": "1",
        "amc_name": "JM Financial Mutual Fund",
        "rating": "1",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.4",
        "returns_3yr": "3.7",
        "returns_5yr": "4.5"
    },
    {
        "scheme_name": "JM Equity Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "5000",
        "expense_ratio": "1.37",
        "fund_size_cr": "11",
        "fund_age_yr": "10",
        "fund_manager": "Asit Bhandarkar",
        "sortino": "3.79",
        "alpha": "5.95",
        "sd": "17.44",
        "beta": "1",
        "sharpe": "1.4",
        "risk_level": "6",
        "amc_name": "JM Financial Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "8",
        "returns_3yr": "29.5",
        "returns_5yr": "11.2"
    },
    {
        "scheme_name": "Kotak Balanced Advantage Fund",
        "min_sip": "1000",
        "min_lumpsum": "1000",
        "expense_ratio": "0.48",
        "fund_size_cr": "14279",
        "fund_age_yr": "5",
        "fund_manager": "Harish Krishnan",
        "sortino": "4.01",
        "alpha": "3.56",
        "sd": "8.76",
        "beta": "0.56",
        "sharpe": "1.59",
        "risk_level": "6",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Dynamic Asset Allocation or Balanced Advantage",
        "returns_1yr": "5.5",
        "returns_3yr": "18.1",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Kotak Debt Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.44",
        "fund_size_cr": "1650",
        "fund_age_yr": "10",
        "fund_manager": "Devender Singhal",
        "sortino": "3.44",
        "alpha": "4.79",
        "sd": "4.73",
        "beta": "0.7",
        "sharpe": "2.06",
        "risk_level": "4",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "6.1",
        "returns_3yr": "14.3",
        "returns_5yr": "10"
    },
    {
        "scheme_name": "Kotak Equity Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.43",
        "fund_size_cr": "21917",
        "fund_age_yr": "10",
        "fund_manager": "Hiten Shah",
        "sortino": "1.46",
        "alpha": "1.66",
        "sd": "0.75",
        "beta": "0.54",
        "sharpe": "1.26",
        "risk_level": "1",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.8",
        "returns_3yr": "4.9",
        "returns_5yr": "5.6"
    },
    {
        "scheme_name": "Kotak Equity Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.58",
        "fund_size_cr": "3269",
        "fund_age_yr": "8",
        "fund_manager": "Pankaj Tibrewal",
        "sortino": "3.89",
        "alpha": "7.32",
        "sd": "11.76",
        "beta": "0.79",
        "sharpe": "1.86",
        "risk_level": "6",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "rating": "0",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "5",
        "returns_3yr": "26.9",
        "returns_5yr": "12.8"
    },
    {
        "scheme_name": "Kotak Equity Savings Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "1.02",
        "fund_size_cr": "2097",
        "fund_age_yr": "8",
        "fund_manager": "Devender Singhal",
        "sortino": "4.22",
        "alpha": "4.5",
        "sd": "5.64",
        "beta": "0.79",
        "sharpe": "1.8",
        "risk_level": "4",
        "amc_name": "Kotak Mahindra Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "6.6",
        "returns_3yr": "14.4",
        "returns_5yr": "9.2"
    },
    {
        "scheme_name": "LIC MF Arbitrage Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.31",
        "fund_size_cr": "27",
        "fund_age_yr": "4",
        "fund_manager": "Jaiprakash Toshniwal",
        "sortino": "0.67",
        "alpha": "1.23",
        "sd": "0.78",
        "beta": "0.6",
        "sharpe": "0.55",
        "risk_level": "1",
        "amc_name": "LIC Mutual Fund",
        "rating": "2",
        "category": "Hybrid",
        "sub_category": "Arbitrage Mutual Funds",
        "returns_1yr": "5.5",
        "returns_3yr": "4.4",
        "returns_5yr": ""
    },
    {
        "scheme_name": "LIC MF Debt Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "1.34",
        "fund_size_cr": "61",
        "fund_age_yr": "10",
        "fund_manager": "Karan Desai",
        "sortino": "2.11",
        "alpha": "-0.54",
        "sd": "4.14",
        "beta": "0.61",
        "sharpe": "0.92",
        "risk_level": "4",
        "amc_name": "LIC Mutual Fund",
        "rating": "3",
        "category": "Hybrid",
        "sub_category": "Conservative Hybrid Mutual Funds",
        "returns_1yr": "2.5",
        "returns_3yr": "8.1",
        "returns_5yr": "6.7"
    },
    {
        "scheme_name": "LIC MF Equity Hybrid Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "1.43",
        "fund_size_cr": "378",
        "fund_age_yr": "10",
        "fund_manager": "Karan Desai",
        "sortino": "2.26",
        "alpha": "-2.85",
        "sd": "11.49",
        "beta": "0.77",
        "sharpe": "0.99",
        "risk_level": "6",
        "amc_name": "LIC Mutual Fund",
        "rating": "1",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "-0.5",
        "returns_3yr": "15.1",
        "returns_5yr": "8.3"
    },
    {
        "scheme_name": "Mahindra Manulife Aggressive Hybrid Fund",
        "min_sip": "500",
        "min_lumpsum": "1000",
        "expense_ratio": "0.65",
        "fund_size_cr": "615",
        "fund_age_yr": "4",
        "fund_manager": "Fatema Pacha",
        "sortino": "3.57",
        "alpha": "4.52",
        "sd": "12.44",
        "beta": "0.85",
        "sharpe": "1.62",
        "risk_level": "6",
        "amc_name": "Mahindra Manulife Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Aggressive Hybrid Mutual Funds",
        "returns_1yr": "2.7",
        "returns_3yr": "24.6",
        "returns_5yr": ""
    },
    {
        "scheme_name": "Mahindra Manulife Equity Savings Fund",
        "min_sip": "500",
        "min_lumpsum": "1000",
        "expense_ratio": "0.7",
        "fund_size_cr": "418",
        "fund_age_yr": "6",
        "fund_manager": "Fatema Pacha",
        "sortino": "3.1",
        "alpha": "3.84",
        "sd": "8.16",
        "beta": "1.24",
        "sharpe": "1.56",
        "risk_level": "4",
        "amc_name": "Mahindra Manulife Mutual Fund",
        "rating": "4",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "1.7",
        "returns_3yr": "32.4",
        "returns_5yr": "13.3"
    },
    {
        "scheme_name": "Mirae Asset Equity Savings Fund",
        "min_sip": "1000",
        "min_lumpsum": "5000",
        "expense_ratio": "0.43",
        "fund_size_cr": "573",
        "fund_age_yr": "4",
        "fund_manager": "Harshad Borawake",
        "sortino": "4.03",
        "alpha": "4.3",
        "sd": "7.17",
        "beta": "1.06",
        "sharpe": "1.66",
        "risk_level": "4",
        "amc_name": "Mirae Asset Mutual Fund",
        "rating": "5",
        "category": "Hybrid",
        "sub_category": "Equity Savings Mutual Funds",
        "returns_1yr": "3.7",
        "returns_3yr": "16.1"
    }
]

const tableBody = document.getElementById('EqTableBody');

Equality.forEach(Equality => {
  const row = document.createElement('tr');
  row.innerHTML = `
    <td>${Equality.scheme_name}</td>
    <td>${Equality.min_sip}</td>
    <td>${Equality.min_lumpsu}</td>
    <td>${Equality.expense_ratio}</td>
    <td>${Equality.fund_size_cr}</td>
    <td>${Equality.rating}</td>
    <td>${Equality.fund_manager}</td>
    <td>${Equality.amc_name}</td>
    <td>${Equality.category}</td>
    <td>${Equality.risk_level}</td>
    <td>${Equality.fund_age_yr}</td>
    <td>${Equality.fund_age_yr}</td>
  `;
  tableBody.appendChild(row);
});